### ISSUE TITLE
[Profession] Copper vein

### ISSUE THREAD

**Issue by moemiki** [ThanokKarabor/Karabor#107]
https://www.burning-crusade.com/database/?search=Copper#objects
      One of these

They are not displayed on minimap via Find Minerals and are non-interactive

**Comment by Azmodeane** [comment]
Which Zone were you in when this occurred? Do you have cords?

**Comment by moemiki** [comment]
I luckily found a node in Elwynn Forest, those "cliffs" south of goldshire

Also to note the scarcity of nodes. Dun Morogh had 0 veins and Loch Modan had 4 Tin veins.
I noticed after going through those zones that copper veins can't be found via Find Minerals

**Comment by Icesythe7** [comment]
deleting cache works
