### ISSUE TITLE
Quest (62) A Spirit Guide

### ISSUE THREAD

**Issue by Letanius** [ThanokKarabor/Karabor#119]
Quest ID 9410

The Ancestral Spirit Wolf (npc=17077) is supposed to ignore all combat and keep walking up the hill. 
Currently, he doesn't. If you don't tag the mob that's attacking before the dog gets hit, he will get one shot. He only has 300 some odd health. 
Here's a link to how this quest is supposed to work
[https://youtu.be/tecIo0MPWVk](url)

Currently, this quest is unable to be completed. 
This is marked as a high priority due to the fact that this chain unlocks the Mag'har rep.

**Comment by Icesythe7** [comment]
fixed
