### ISSUE TITLE
 [Winterfall Runners]

### ISSUE THREAD

**Issue by Enzantel** [ThanokKarabor/Karabor#122]
the 3 Winterfall runner's does not aggro while walking near them. only when i attack them 
![wowscrnshot_032717_162407](https://cloud.githubusercontent.com/assets/26557017/24361311/e7834f4a-1309-11e7-96ed-fde846b0550f.jpg)

**Comment by Icesythe7** [comment]
this is correct according to the comments on the npc 
http://www.wowhead.com/npc=10916/winterfall-runner#comments
