### ISSUE TITLE
[H][Quest] The Ashenvale Hunt x2

### ISSUE THREAD

**Issue by moemiki** [ThanokKarabor/Karabor#130]
Jorn Skyseer
Barrens, 44.9, 59.0
https://www.burning-crusade.com/database/?quest=6382

Senani Thunderheart
Ashenvale, 73,7. 61.6
https://www.burning-crusade.com/database/?npc=12696

Senani's quest can be finished without having done Jorn's quest. Chain bug?

**Comment by Letanius** [comment]
[http://db.vanillagaming.org/?quest=742#wh-comments](url)

This is a standalone quest. The Jorn quest is only a breadcrumb.
