### ISSUE TITLE
Quest [Boiling Blood] hellfire

### ISSUE THREAD

**Issue by Enzantel** [ThanokKarabor/Karabor#14]
[Bleeding Hollow Blood] seems to have to rare droprate, also when i put the blood in the Cursed Cauldron no Cursed Scarab is spawning around it.

Link to a video of the quest if you need:
https://www.youtube.com/watch?v=2nQrUeECQ2w

**Comment by Enzantel** [comment]
https://ibb.co/bRLPva manage to get this to spawn tho, XD

**Comment by Enzantel** [comment]
Also quest in the same area called The Eyes of Grillok after you completed it the buff does not go automatically away, no big deal can just take it of but worth mention

**Comment by ThanokKarabor** [comment]
Fixed! 💃
