### ISSUE TITLE
Gutripper bird elite in nagrand

### ISSUE THREAD

**Issue by Enzantel** [ThanokKarabor/Karabor#15]
Gutripper does not patrol, standing still like on the picture

https://ibb.co/hiuO5a

http://www.wow-pro.com/guidepics/alliance5/gutlor.jpg   (this is hes patrol route) 
https://www.youtube.com/watch?v=67iA3cpfomo              (this video you can somewhat see what hight he is patrolling in.)

**Comment by ThanokKarabor** [comment]
Fixed!
