### ISSUE TITLE
Orb of Translocation 

### ISSUE THREAD

**Issue by Enzantel** [ThanokKarabor/Karabor#16]
i was doing a quest called [Deactivating the spire] in Eversong Woods and i needed to use the orb to teleport up to a platfrom. at the top of the platform it was 2 mobs killing me (yet im higher level then normal) because my pet did not follow. i was researching abit about this and the pet is suppost to get teleported with you. im sure there are other orbs like this, Falcon Watch in hellfire and Firewing Point in terokkar forest that i can think of right now im sure there are more around.

https://ibb.co/fEKedv
https://www.youtube.com/watch?v=2JAvMEwkICg  (this one shows the pet following)

**Comment by Enzantel** [comment]
ops here is the full name of the orb im talking about: Orb of Translocation. Not sure yet if the pet is suppost to follow when its far away like undercity/silvermoon city one.

**Comment by ThanokKarabor** [comment]
Fixed all accross the board :)

**Comment by ThanokKarabor** [comment]
This one was a doozie to fix :O
