### ISSUE TITLE
Death Warrior no spells to bars

### ISSUE THREAD

**Issue by Tearsx** [ThanokKarabor/Karabor#17]
When you are dead then you have no spells to your bars this issue appears to be localized to warrior only.
Other people have tested it out with ohter classes.
![whendeadnobars](https://cloud.githubusercontent.com/assets/26602164/24202933/911087e8-0f14-11e7-8e33-be3ab8120413.jpg)

**Comment by Azmodeane** [comment]
It is how warrior works, I believe. Only your Main bottom bar will be blank. It is because you do not have a stance active while dead.

**Comment by ThanokKarabor** [comment]
Azmodeane is right, since you don't have a stance its just how it works on our server 🗡 

Closing thread.
