### ISSUE TITLE
Teldrassil - Quest Items do not become unable to be gathered after picking up the required amount

### ISSUE THREAD

**Issue by Eitriana** [ThanokKarabor/Karabor#30]
Pretty much as title says. After picking up the required amount of Moonpetal Lily and Hyacinth Mushroom for quest Iverron's Antidote, the items still sparkle for visibility and allow you to click on them to gather them. However it does not allow you to actually pick up more than the required amount, so after the gathering cast bar completes, nothing happens.

Edit: after relogging, no longer sparkling or clickable.

**Comment by Eitriana** [comment]
I'm going to close this because it may have just been an issue with GM mode toggle. I had toggled it off before doing this quest, but after relogging the items didn't behave this way anymore.

**Comment by ThanokKarabor** [comment]
Thanks Eitri :D
