### ISSUE TITLE
Multiple Rank 1 Seal of Righteousness

### ISSUE THREAD

**Issue by Azmodeane** [ThanokKarabor/Karabor#33]
I noticed I have two copies of Rank 1 Seal of Righteousness on my Draenei Paladin. Not sure when it appeared. Noticed it after buying lvl 6 skills
![two of the same rank](https://cloud.githubusercontent.com/assets/20554265/24219520/4f925266-0f04-11e7-9f97-b240b1c28bb7.jpg)

**Comment by ThanokKarabor** [comment]
Fixed this, forgot to update.
