### ISSUE TITLE
Weekly pvp npc's

### ISSUE THREAD

**Issue by Snowie493** [ThanokKarabor/Karabor#4]
The  weekly pvp bg guys that spawns around the world, mostly in citys do spawn all bg's together instead of the bg that actually is the weekly bg.

Screenshot: http://prntscr.com/elr5cu

**Comment by ThanokKarabor** [comment]
Should be fixed now. Just needed to restart the events.

**Comment by ThanokKarabor** [comment]
Still bugged after restart

**Comment by ThanokKarabor** [comment]
Fixed!
