### ISSUE TITLE
Fel Handler and Netherhound

### ISSUE THREAD

**Issue by Letanius** [ThanokKarabor/Karabor#50]
There is a Netherhound that is not tied to it's Fel Handler being pulled at 70,46 of Hellfire Penninsula. 
All Netherhounds are supposed to be tethered to their Fel Handlers. 

This appears to be a one pack instance as the other mobs all pulled as intended. 

**edit this appeared to be a one off problem, closing ticket.

**Comment by ThanokKarabor** [comment]
I looked into this more and found a chaining issue. Fixed.
