### ISSUE TITLE
The blood Furnace

### ISSUE THREAD

**Issue by Enzantel** [ThanokKarabor/Karabor#88]
the event part before second boss with the lever does not work, eatch wave have some extra mobs coming out at the same time from the other jail that comes after the ones we just killed at the.

![wowscrnshot_032517_033748](https://cloud.githubusercontent.com/assets/26557017/24318859/1ccca5f6-110d-11e7-9526-011059917458.jpg)

**Comment by ThanokKarabor** [comment]
Fixed the event, still working on getting the mobs auto aggro'd onto the group.
