### ISSUE TITLE
[Stolen Booty] barrens quest

### ISSUE THREAD

**Issue by Enzantel** [ThanokKarabor/Karabor#92]
the 2 items i need to loot for the quest is not possible to click on

![wowscrnshot_032517_152255](https://cloud.githubusercontent.com/assets/26557017/24323008/16fe5b76-116f-11e7-9672-b18ccc6fef58.jpg)

![wowscrnshot_032517_152314](https://cloud.githubusercontent.com/assets/26557017/24323009/1c880be6-116f-11e7-8b92-7ea17773889a.jpg)

**Comment by Enzantel** [comment]
this was on Lua, works on the old core. closing for now

**Comment by Enzantel** [comment]
nvm turns out it still dont work on old core :)

**Comment by Icesythe7** [comment]
will fix when thanok stops destroying the server

**Comment by Icesythe7** [comment]
seems to be working fine for me with lua core finished it as intended
