### ISSUE TITLE
Honor Hold NPCs

### ISSUE THREAD

**Issue by reversalTheMage** [ThanokKarabor/Karabor#94]
Theres 4 "Nethergarde Infantry" in the Honorhold inn relaxing but two are facing away table and it looks pretty awkward
![wowscrnshot_032517_155035](https://cloud.githubusercontent.com/assets/26674982/24323781/ef2b77e2-1172-11e7-8c97-000ca83b1485.jpg)

**Comment by Icesythe7** [comment]
fixed
